export const valuesSpeedHeight = [
    { value: 0, label: 'One' },
    { value: 1, label: 'One' },
    { value: 2, label: 'Two' },
    { value: 3, label: 'Three' },
    { value: 4, label: 'Four' },
    { value: 5, label: 'Five' },
    { value: 6, label: 'Five' },
    { value: 7, label: 'Five' },
    { value: 8, label: 'Five' },
    { value: 9, label: 'Five' },
    { value: 10, label: 'Five' },
    { value: 11, label: 'Five' },
    { value: 12, label: 'Five' },
    { value: 13, label: 'Five' },
    { value: 14, label: 'Five' },
    { value: 15, label: 'Five' },
    { value: 16, label: 'Five' },
    { value: 17, label: 'Five' },
    { value: 18, label: 'Five' },
    { value: 19, label: 'Five' },
    { value: 20, label: 'Five' },
];

export const valuesSpin = [
    { value: -10, label: 'One' },
    { value: -9, label: 'Two' },
    { value: -8, label: 'Three' },
    { value: -7, label: 'Four' },
    { value: -6, label: 'Five' },
    { value: -5, label: 'Five' },
    { value: -4, label: 'Five' },
    { value: -3, label: 'Five' },
    { value: -2, label: 'Five' },
    { value: -1, label: 'Five' },
    { value: 0, label: 'Five' },
    { value: 1, label: 'Five' },
    { value: 2, label: 'Five' },
    { value: 3, label: 'Five' },
    { value: 4, label: 'Five' },
    { value: 5, label: 'Five' },
    { value: 6, label: 'Five' },
    { value: 7, label: 'Five' },
    { value: 8, label: 'Five' },
    { value: 9, label: 'Five' },
    { value: 10, label: 'Five' },
];